const quotes = [
    "Je m’appelle frikandel.",
    "I don't know, and um like I said in the beginning of this press conference, I get really tired of all the questions, so if I get a few more, I might headbutt someone.",
    "Because I'm Dutch.",
    "Hello everyone, eaehh.",
    "Thank you, Danny.",
    "Ki ki aye.",
    "Daniel, look!",
    "I believe I can fly, I believe I can touch the sky…okay, that's enough.",
    "Get me to the chopper.",
    "Man, is this guy blind?",
    "Ay ay ay, these tyres are already vibrating like I flat-spotted for 300 meters.",
    "Nah, I'll just visit the dentist after the weekend.",
    "I hate this fucking DRS.",
    "Yeah, I'm not even gonna say it, wtf happened.",
    "I couldn't do anything there.",
    "Wow, nice gap that.",
    "That's what you get when you don't leave the space.",
    "Mate, we all have no grip.",
    "What an idiot.",
    "You don't need to finish it, it's Charles.",
    "It was just to put the pressure on Helmut to give me a better contract.",
    "Ni hao!",
    "Why is it so spikey? What is it? Now I can not hold it anymore.",
    "Rapupupup wauuu.",
    "Quack quack.",
    "My dad did that once to a mechanic.",
    "He pushed me, I pushed him, he pushed me off the track.",
    "The only place that matters is first",
    "I always try to get the best result out of it, I'm not there to just sit second or sit third",
    "Mistakes happen, and they happen to the best of us",
    "I just want to do the best I can every time",
    "I think you can improve on everything; you're never perfect",
    "simply lovely"
];

module.exports = quotes;
